(function(){
  'use strict';
  const content=window.IEQ_CONTENT||{};
  const fields={
    'index.html':[['home_title_before','Título: primeira linha'],['home_title_middle','Título: início da segunda linha'],['home_title_accent','Título: trecho coral'],['home_intro','Texto de apresentação'],['home_photo','Foto principal'],['fachada_photo','Foto: fachada'],['kids_photo','Foto: Kids'],['casais_photo','Foto: Casais'],['jovens_photo','Foto: Jovens'],['mulheres_photo','Foto: Mulheres'],['kids_text','Texto: Kids'],['casais_text','Texto: Casais'],['jovens_text','Texto: Jovens'],['mulheres_text','Texto: Mulheres']],
    'horarios.html':[['sunday_morning','Domingo: manhã'],['sunday_evening','Domingo: noite'],['tuesday_time','Terça-feira'],['wednesday_time','Quarta-feira'],['sunday_first','1º domingo'],['sunday_second','2º domingo'],['sunday_third','3º domingo'],['sunday_last','4º ou último domingo'],['culto_photo','Foto do culto'],['fachada_photo','Foto: fachada']],
    'ministerios.html':[['kids_photo','Foto: Kids'],['casais_photo','Foto: Casais'],['jovens_photo','Foto: Jovens'],['mulheres_photo','Foto: Mulheres'],['kids_text','Texto: Kids'],['casais_text','Texto: Casais'],['jovens_text','Texto: Jovens'],['mulheres_text','Texto: Mulheres'],['kids_photo_2','Foto 2: Kids'],['kids_photo_3','Foto 3: Kids'],['kids_photo_4','Foto 4: Kids'],['casais_photo_2','Foto 2: Casais'],['casais_photo_3','Foto 3: Casais'],['casais_photo_4','Foto 4: Casais'],['jovens_photo_2','Foto 2: Jovens'],['jovens_photo_3','Foto 3: Jovens'],['jovens_photo_4','Foto 4: Jovens'],['mulheres_photo_2','Foto 2: Mulheres'],['mulheres_photo_3','Foto 3: Mulheres'],['mulheres_photo_4','Foto 4: Mulheres']],
    'localizacao.html':[['address','Endereço completo']],
    'contato.html':[['whatsapp','Número do WhatsApp'],['instagram','Perfil do Instagram'],['contato_photo','Foto da página'],['comunidade_photo','Foto: culto na faixa inferior'],['sunday_morning','Domingo: manhã'],['sunday_evening','Domingo: noite'],['tuesday_time','Terça-feira'],['wednesday_time','Quarta-feira']],
    'visita.html':[['visita_photo','Foto da primeira visita']]
  };
  const descriptions={home_title_before:'Início: primeira linha do título, texto escuro',home_title_middle:'Início: início da segunda linha, texto escuro',home_title_accent:'Início: segunda linha do título, texto coral',home_intro:'Início: parágrafo abaixo do título',home_photo:'Início: imagem grande ao lado do convite',kids_photo:'Faixa de ministérios: Kids',casais_photo:'Faixa de ministérios: Casais',jovens_photo:'Faixa de ministérios: Jovens',mulheres_photo:'Faixa de ministérios: Mulheres',culto_photo:'Horários: imagem grande à direita',contato_photo:'Contato: imagem entre os canais e o formulário',visita_photo:'Primeira visita: imagem grande à direita',kids_photo_2:'Ministérios: carrossel do Kids, foto 2',kids_photo_3:'Ministérios: carrossel do Kids, foto 3',kids_photo_4:'Ministérios: carrossel do Kids, foto 4',casais_photo_2:'Ministérios: carrossel de Casais, foto 2',casais_photo_3:'Ministérios: carrossel de Casais, foto 3',casais_photo_4:'Ministérios: carrossel de Casais, foto 4',jovens_photo_2:'Ministérios: carrossel de Jovens, foto 2',jovens_photo_3:'Ministérios: carrossel de Jovens, foto 3',jovens_photo_4:'Ministérios: carrossel de Jovens, foto 4',mulheres_photo_2:'Ministérios: carrossel de Mulheres, foto 2',mulheres_photo_3:'Ministérios: carrossel de Mulheres, foto 3',mulheres_photo_4:'Ministérios: carrossel de Mulheres, foto 4',address:'Localização: endereço escrito, mapa e botão de rota',whatsapp:'Contato: botão de WhatsApp',instagram:'Contato: link do Instagram'};
  const imageFields=new Set(['kids_photo_2','kids_photo_3','kids_photo_4','casais_photo_2','casais_photo_3','casais_photo_4','jovens_photo_2','jovens_photo_3','jovens_photo_4','mulheres_photo_2','mulheres_photo_3','mulheres_photo_4','home_photo','kids_photo','casais_photo','jovens_photo','mulheres_photo','culto_photo','comunidade_photo','fachada_photo','visita_photo','contato_photo']);
  const pageSelect=document.getElementById('page-select'),fieldSelect=document.getElementById('field-select'),editor=document.getElementById('field-editor'),frame=document.getElementById('site-preview'),status=document.getElementById('admin-status');
  let draft={};try{draft=JSON.parse(localStorage.getItem('ieqt_draft')||'{}');}catch(_){draft={};}
  const data=()=>({...content,...draft});
  function save(){try{localStorage.setItem('ieqt_draft',JSON.stringify(draft));status.textContent='Rascunho salvo neste navegador.';return true;}catch(_){status.textContent='Espaço do navegador insuficiente. Use uma foto menor.';return false;}}
  function selectField(){const key=fieldSelect.value;const label=fieldSelect.selectedOptions[0]?.textContent||'';document.getElementById('edit-place').textContent=(descriptions[key]||`${pageSelect.selectedOptions[0].textContent}: ${label}`)+'. A área fica contornada em coral na prévia.';editor.replaceChildren();if(imageFields.has(key)){const img=document.createElement('img');img.className='upload-preview';img.alt='Prévia da foto selecionada';img.src=data()[key]||'./assets/logo-480.webp';editor.append(img);const help=document.createElement('p');help.className='field-help';help.textContent='Escolha uma foto real da igreja. O arquivo será reduzido para a página carregar bem.';editor.append(help);const input=document.createElement('input');input.type='file';input.accept='image/jpeg,image/png,image/webp';input.id='photo-file';editor.append(input);input.addEventListener('change',async()=>{const file=input.files[0];if(!file)return;try{draft[key]=await compress(file);if(save()){img.src=draft[key];sendPreview();highlight();}}catch(_){status.textContent='Não foi possível ler essa foto.';}});}else{const area=document.createElement(key==='home_intro'||key.endsWith('_text')?'textarea':'input');area.id='edit-value';area.value=data()[key]||'';area.maxLength=key==='address'?200:500;editor.append(area);area.addEventListener('input',()=>{draft[key]=area.value;sendPreview();highlight();});}highlight();}
  function populate(){fieldSelect.replaceChildren();fields[pageSelect.value].forEach(([key,label])=>{const option=document.createElement('option');option.value=key;option.textContent=label;fieldSelect.append(option);});selectField();}
  function sendPreview(){frame.contentWindow?.postMessage({type:'ieqt-preview',values:data()},location.origin);}
  function highlight(){const key=fieldSelect.value;const doc=frame.contentDocument;if(!doc)return;doc.querySelectorAll('.admin-highlight').forEach(el=>el.classList.remove('admin-highlight'));const target=doc.querySelector(`[data-content="${key}"],[data-image="${key}"],[data-edit-target="${key}"]`);if(target){target.classList.add('admin-highlight');target.scrollIntoView({behavior:'smooth',block:'center'});}}
  function openPage(){frame.src=`./${pageSelect.value}?preview=1`;}
  frame.addEventListener('load',()=>{sendPreview();setTimeout(highlight,150);});
  pageSelect.addEventListener('change',()=>{populate();openPage();});fieldSelect.addEventListener('change',selectField);
  document.getElementById('save-draft').addEventListener('click',()=>{if(save()){sendPreview();highlight();}});
  document.getElementById('reset-field').addEventListener('click',()=>{delete draft[fieldSelect.value];save();selectField();sendPreview();});
  document.getElementById('export-draft').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(data(),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ieqt-tapajos-rascunho.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);});
  document.querySelectorAll('[data-width]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-width]').forEach(el=>el.classList.toggle('is-active',el===button));document.getElementById('preview-frame').classList.toggle('is-mobile',button.dataset.width==='mobile');}));
  async function compress(file){if(file.size>20*1024*1024)throw Error('file');const bitmap=await createImageBitmap(file);const scale=Math.min(1,1280/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();let quality=.78;let url=canvas.toDataURL('image/jpeg',quality);while(url.length>330000&&quality>.35){quality-=.08;url=canvas.toDataURL('image/jpeg',quality);}if(url.length>330000)throw Error('too large');return url;}
  populate();
})();
