window.IEQ_CONTENT = {
  home_title_before: 'Uma casa',
  home_title_middle: 'para',
  home_title_accent: 'viver a fé.',
  home_intro: 'Gente real, encontros verdadeiros e um Deus que transforma a nossa cidade.',
  home_photo: './assets/ilustracao-home-worship.jpg',
  kids_photo: './assets/ilustracao-kids.jpg',
  casais_photo: './assets/ilustracao-casais.jpg',
  jovens_photo: './assets/ilustracao-jovens.jpg',
  mulheres_photo: './assets/ilustracao-mulheres.jpg',
  culto_photo: './assets/ilustracao-home-worship.jpg',
  comunidade_photo: './assets/ilustracao-culto.jpg',
  fachada_photo: './assets/ilustracao-fachada.jpg',
  visita_photo: './assets/ilustracao-visita.jpg',
  contato_photo: './assets/ilustracao-home-worship.jpg',
  kids_text: 'Uma geração que conhece, ama e serve a Jesus.',
  casais_text: 'Relacionamentos fortalecidos para uma vida com propósito.',
  jovens_text: 'Amizade, verdade e um chamado maior.',
  mulheres_text: 'Vida, comunhão e propósito em todas as estações.',
  sunday_morning: '8h30',
  sunday_evening: '18h30',
  tuesday_time: '19h30',
  wednesday_time: '19h30',
  sunday_first: 'Santa Ceia',
  sunday_second: 'Culto da Família',
  sunday_third: 'Culto de Missões',
  sunday_last: 'Celebração de Células',
  address: 'R. Anhembi, 36 - Tapanã, Belém - PA, 66833-310',
  whatsapp: '5591982808543',
  instagram: 'ieqtapajos'
};
