window.IEQ_CONTENT = {
  home_title_before: 'Uma casa',
  home_title_middle: 'para',
  home_title_accent: 'viver a fé.',
  home_intro: 'Gente real, encontros verdadeiros e um Deus que transforma a nossa cidade.',
  home_photo: './assets/ilustracao-home-worship.webp',
  kids_photo: './assets/ilustracao-kids.webp',
  casais_photo: './assets/ilustracao-casais.webp',
  jovens_photo: './assets/ilustracao-jovens.webp',
  mulheres_photo: './assets/ilustracao-mulheres.webp',
  culto_photo: './assets/ilustracao-home-worship.webp',
  comunidade_photo: './assets/ilustracao-culto.webp',
  fachada_photo: './assets/ilustracao-fachada.webp',
  visita_photo: './assets/ilustracao-visita.webp',
  contato_photo: './assets/ilustracao-home-worship.webp',
  kids_photo_2: './assets/ilustracao-kids-2.webp',
  kids_photo_3: './assets/ilustracao-kids-3.webp',
  kids_photo_4: './assets/ilustracao-kids-4.webp',
  casais_photo_2: './assets/ilustracao-casais-2.webp',
  casais_photo_3: './assets/ilustracao-casais-3.webp',
  casais_photo_4: '',
  jovens_photo_2: './assets/ilustracao-jovens-2.webp',
  jovens_photo_3: '',
  jovens_photo_4: '',
  mulheres_photo_2: './assets/ilustracao-mulheres-2.webp',
  mulheres_photo_3: './assets/ilustracao-mulheres-3.webp',
  mulheres_photo_4: '',
  kids_text: 'Uma geração que conhece, ama e serve a Jesus.',
  casais_text: 'Relacionamentos fortalecidos para uma vida com propósito.',
  jovens_text: 'Amizade, verdade e um chamado maior.',
  mulheres_text: 'Vida, comunhão e propósito em todas as estações.',
  sunday_morning: '8h30',
  sunday_evening: '18h30',
  tuesday_time: '19h30',
  wednesday_time: '19h30',
  sunday_first: 'Santa Ceia',
  sunday_second: 'Culto da Família',
  sunday_third: 'Culto de Missões',
  sunday_last: 'Celebração de Células',
  address: 'R. Anhembi, 36 - Tapanã, Belém - PA, 66833-310',
  whatsapp: '5591982808543',
  instagram: 'ieqtapajos'
};
